### ISSUE TITLE
You cannot send generic transaction from Multisig

### ISSUE THREAD

**Issue by chfast** [imapp-pl/golem-crowdfunding#52]
That means:
- you cannot deploy Crowdfunding contract,
- you don't have control over GNT and e.g. cannot start migration.

It might be Ethereum Wallet UI issue only.

**Comment by chfast** [comment]
Please consider this versions:
https://github.com/ConsenSys/MultiSigWallet
https://github.com/ethereum/dapp-bin/blob/master/wallet/wallet.sol

**Comment by paulperegud** [comment]
added consensys wallet in #93
