### ISSUE TITLE
dust spam attack?

### ISSUE THREAD

**Issue by paulperegud** [imapp-pl/golem-crowdfunding#77]
Scenario is as following: a lot of small transactions is made from different accounts, blowing up size of balances array. Can this affect other funders?

I see three possibilities.

a) gas cost of creating one more entry in balances is not a constant function of size(balances).  
b) gas cost is constant, but work is not constant and this operation can be used to spam network  
c) no worries, ETH has withered more complicated attacks

**Comment by chfast** [comment]
Storage size does not influence the cost (like in b). This is Ethereum network issue, not the contract issue.
