### ISSUE TITLE
Maybe use populus for testing?

### ISSUE THREAD

**Issue by pipermerriam** [imapp-pl/golem-crowdfunding#82]
Someone pointed me at your repository noting that the tests are written in python.  I was curious if your team knew about [populus](https://github.com/pipermerriam/populus) which might take some of the overhead out of your testing setup?

**Comment by pipermerriam** [comment]
looks like #1 covers this.

**Comment by miohtama** [comment]
I highly recommend Populus, as py.test based test fixtures and functions make it easier, more elegant, to stress out smart contract functionality. This simplicity especially pays off when dealing with smart contracts where one doesn't want to create hard-to-understand logic.
